---
name: zaincash_integration
description: A new Flutter project.
publish_to: none
version: 0.1.0
environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'
dependencies:
  cloud_firestore: ^4.17.3
  dart_jsonwebtoken: ^2.14.0
  dio: ^5.4.3+1
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  get: ^4.6.6
  http: ^1.2.1
  logger: ^2.2.0
  sizer: ^2.0.15
  uuid: ^4.4.0
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
